import React from "react";
import { TrendingUp, Activity, Zap, BarChart3 } from "lucide-react";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, LineChart, Line, PieChart, Pie, Cell } from "recharts";

// Mock data for charts
const USAGE_TREND = [
  { month: "Nov", generations: 6200, apiCalls: 8500 },
  { month: "Dec", generations: 7100, apiCalls: 9800 },
  { month: "Jan", generations: 7800, apiCalls: 10200 },
  { month: "Feb", generations: 8500, apiCalls: 11500 },
  { month: "Mar", generations: 9241, apiCalls: 12800 },
];

const PLATFORM_DISTRIBUTION = [
  { name: "LinkedIn", value: 35, color: "#0A66C2" },
  { name: "Instagram", value: 28, color: "#E4405F" },
  { name: "Facebook", value: 18, color: "#1877F2" },
  { name: "Twitter/X", value: 12, color: "#1DA1F2" },
  { name: "YouTube", value: 7, color: "#FF0000" },
];

const CONTENT_TYPES = [
  { type: "Text Posts", count: 4520, percentage: 45 },
  { type: "Image Captions", count: 2850, percentage: 28 },
  { type: "Video Scripts", count: 1680, percentage: 17 },
  { type: "Carousels", count: 1010, percentage: 10 },
];

const TOP_COMPANIES = [
  { name: "Uden Tech", generations: 2840, growth: "+24%" },
  { name: "Pixel Works", generations: 2150, growth: "+18%" },
  { name: "Brandify Co.", generations: 1680, growth: "+32%" },
  { name: "Nova Labs", generations: 980, growth: "+45%" },
  { name: "MarkNet", generations: 420, growth: "-8%" },
];

const STATS = [
  { label: "Total API Calls (Month)", value: "12,847", icon: Zap, change: "+18% vs last month", trend: "up" },
  { label: "Avg. Response Time", value: "1.2s", icon: Activity, change: "-0.3s improvement", trend: "up" },
  { label: "Success Rate", value: "98.7%", icon: TrendingUp, change: "+0.5% vs last month", trend: "up" },
  { label: "Avg. Generations/Company", value: "782", icon: BarChart3, change: "+124 vs last month", trend: "up" },
];

export default function SuperAdminAnalytics() {
  return (
    <div className="space-y-6 max-w-7xl">
      <div>
        <h1 className="font-display text-2xl font-bold text-foreground">Analytics</h1>
        <p className="text-muted-foreground text-sm">Platform usage insights and trends</p>
      </div>

      {/* Performance Stats */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
        {STATS.map(({ label, value, icon: Icon, change, trend }) => (
          <div key={label} className="bg-card border border-border rounded-xl p-5">
            <div className="flex items-center justify-between mb-3">
              <p className="text-sm text-muted-foreground">{label}</p>
              <div className="w-8 h-8 rounded-lg bg-primary/10 flex items-center justify-center">
                <Icon className="w-4 h-4 text-primary" />
              </div>
            </div>
            <p className="font-display text-2xl font-bold text-foreground">{value}</p>
            <p className={`text-xs mt-1 ${trend === "up" ? "text-green-400" : "text-red-400"}`}>
              {change}
            </p>
          </div>
        ))}
      </div>

      {/* Charts Row 1 */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Usage Trend */}
        <Card>
          <CardHeader>
            <CardTitle className="text-base">Generation Trend</CardTitle>
            <CardDescription>Monthly content generation volume</CardDescription>
          </CardHeader>
          <CardContent>
            <ResponsiveContainer width="100%" height={300}>
              <LineChart data={USAGE_TREND}>
                <CartesianGrid strokeDasharray="3 3" stroke="hsl(var(--border))" />
                <XAxis dataKey="month" stroke="hsl(var(--muted-foreground))" />
                <YAxis stroke="hsl(var(--muted-foreground))" />
                <Tooltip 
                  contentStyle={{ 
                    backgroundColor: "hsl(var(--card))", 
                    border: "1px solid hsl(var(--border))",
                    borderRadius: "8px"
                  }} 
                />
                <Line type="monotone" dataKey="generations" stroke="hsl(var(--primary))" strokeWidth={2} />
              </LineChart>
            </ResponsiveContainer>
          </CardContent>
        </Card>

        {/* Platform Distribution */}
        <Card>
          <CardHeader>
            <CardTitle className="text-base">Platform Distribution</CardTitle>
            <CardDescription>Content generated by platform</CardDescription>
          </CardHeader>
          <CardContent>
            <ResponsiveContainer width="100%" height={300}>
              <PieChart>
                <Pie
                  data={PLATFORM_DISTRIBUTION}
                  cx="50%"
                  cy="50%"
                  labelLine={false}
                  label={({ name, percent }) => `${name} ${(percent * 100).toFixed(0)}%`}
                  outerRadius={100}
                  fill="#8884d8"
                  dataKey="value"
                >
                  {PLATFORM_DISTRIBUTION.map((entry, index) => (
                    <Cell key={`cell-${index}`} fill={entry.color} />
                  ))}
                </Pie>
                <Tooltip />
              </PieChart>
            </ResponsiveContainer>
          </CardContent>
        </Card>
      </div>

      {/* Charts Row 2 */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Content Types */}
        <Card>
          <CardHeader>
            <CardTitle className="text-base">Content Types</CardTitle>
            <CardDescription>Distribution by content format</CardDescription>
          </CardHeader>
          <CardContent>
            <div className="space-y-4">
              {CONTENT_TYPES.map(({ type, count, percentage }) => (
                <div key={type}>
                  <div className="flex items-center justify-between mb-2">
                    <span className="text-sm text-foreground">{type}</span>
                    <span className="text-sm text-muted-foreground">{count} ({percentage}%)</span>
                  </div>
                  <div className="w-full bg-secondary rounded-full h-2">
                    <div
                      className="bg-primary h-2 rounded-full transition-all"
                      style={{ width: `${percentage}%` }}
                    />
                  </div>
                </div>
              ))}
            </div>
          </CardContent>
        </Card>

        {/* Top Companies */}
        <Card>
          <CardHeader>
            <CardTitle className="text-base">Top Companies by Usage</CardTitle>
            <CardDescription>Most active companies this month</CardDescription>
          </CardHeader>
          <CardContent>
            <div className="space-y-4">
              {TOP_COMPANIES.map(({ name, generations, growth }) => (
                <div key={name} className="flex items-center justify-between">
                  <div>
                    <p className="text-sm font-medium text-foreground">{name}</p>
                    <p className="text-xs text-muted-foreground">{generations} generations</p>
                  </div>
                  <span className={`text-sm font-medium ${growth.startsWith("+") ? "text-green-400" : "text-red-400"}`}>
                    {growth}
                  </span>
                </div>
              ))}
            </div>
          </CardContent>
        </Card>
      </div>

      {/* API Usage Chart */}
      <Card>
        <CardHeader>
          <CardTitle className="text-base">API Call Volume</CardTitle>
          <CardDescription>Total API calls over time</CardDescription>
        </CardHeader>
        <CardContent>
          <ResponsiveContainer width="100%" height={300}>
            <BarChart data={USAGE_TREND}>
              <CartesianGrid strokeDasharray="3 3" stroke="hsl(var(--border))" />
              <XAxis dataKey="month" stroke="hsl(var(--muted-foreground))" />
              <YAxis stroke="hsl(var(--muted-foreground))" />
              <Tooltip 
                contentStyle={{ 
                  backgroundColor: "hsl(var(--card))", 
                  border: "1px solid hsl(var(--border))",
                  borderRadius: "8px"
                }} 
              />
              <Bar dataKey="apiCalls" fill="hsl(var(--primary))" radius={[4, 4, 0, 0]} />
            </BarChart>
          </ResponsiveContainer>
        </CardContent>
      </Card>
    </div>
  );
}
